config/routes.rb
Rails.application.routes.draw do
  resources :lists, only: %i[index show new create] do
    resources :bookmarks, only: %i[new create]
  end
  resources :bookmarks, only: %i[destroy]
  root 'lists#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: true
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, presence: true
  validates :title, uniqueness: true
  validates :overview, presence: true
  has_many :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: %i[new create]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[show destroy]

  def index
    @lists = List.all
  end

  def show; end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<h1>Add a movie in <%= @list.name %></h1>
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie, selected: 1%>
  <%= f.submit "Submit bookmark", class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Movie lists</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <%= link_to "My lists", lists_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "New list", new_list_path, class: "nav-link" %>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/lists/index.html.erb
<h1>Lists</h1>
<div class="row row-cols-3">
  <% @lists.each do |l| %>
    <%= link_to (list_path(l)) do %>
    <% url = l.photo.attached? ? l.photo.key : "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg"%>
      <div class="card-category col" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path url, width: 400, height: 300, crop: :fill %>)">
        <%= l.name %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/lists/new.html.erb
<h1>New list</h1>
<%= simple_form_for(@list) do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.button :submit, class: "btn-primary" %>
<% end %>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>
<div class="row row-cols-3">
  <% @list.bookmarks.each do |bookmark| %>
    <div class="card-product">
      <%= image_tag(bookmark.movie.poster_url) %>
      <div class="card-product-infos">
        <h2><%= bookmark.movie.title %></h2>
        <p><%= bookmark.movie.overview %></p>
        <small><%= bookmark.comment %></small>
      </div>
      <%= link_to 'Delete', list_path(@list), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-danger"%>
    </div>
  <% end %>
</div>
<%= link_to "add a movie", new_list_bookmark_path(@list), class: "btn btn-success mt-3" %>